### ISSUE TITLE
Bug when student requests an invitation to an invite-only course

### ISSUE THREAD

**Issue by vvandenschrieck** [TLCA-project/tlca-frontend#12]
Context : 
  - Connected user with student account
  - On an invite-only course page, push on "request invitation button"

Output : 
  - No reaction from the GUI.  
  - JS console : Code 400 - Bad request : [{message: "Cannot query field "date" on type "Registration".",…}]

**Comment by combefis** [comment]
Thank you @vvandenschrieck for reporting this bug.

The issue was in a wrong GraphQL query that used the 'date' field for registrations, but this latter had been changed to 'datetime' in a previous refactoring. It has been solved by commit 58d068f407b7349abe49eebf31947550fc3b9f97 which has been merged into develop and main branches (resulting in the release 1.0.4).

Note that a similar issue was present for registrations (for public courses) and it has been solved at the same time, in commit b4759dbbb0f3c6bd18270c0f33df2f8cac46321a.
